apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::202584583121:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-C85T5KR8IBMM
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      -system:masters
      rolearn: arn:aws:iam::202584583121:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-22T14:50:17Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2021-01-22T14:50:17Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1447"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2fb32165-f504-4c91-877f-d221f5c9d15c
